version: 0.2

phases:
 install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies
      - pip install awscli
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 676206907395.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Starting pre_build phase"
      - aws sts get-caller-identity
      - echo "Updating kubeconfig for EKS..."
      - mkdir -p ./kube
      - aws eks update-kubeconfig --region ap-south-1 --name interesting-disco-party --kubeconfig ./kube/config
      - export KUBECONFIG=./kube/config
      - echo "Contents of kubeconfig:"
      - cat ./kube/config
      - echo "Testing kubectl access..."
      - kubectl get nodes

  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"power-tools","imageUri":"%s"}]' $REPOSITORY_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - k8r/deployment.yaml
    - k8r/service.yaml
