version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog
      - REPOSITORY_URI=676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Updating kubeconfig for EKS...
      - aws eks update-kubeconfig --region ap-south-1 --name interesting-disco-party --kubeconfig ~/.kube/config
      - echo testing k8r connections
      - kubectl get nodes --kubeconfig ~/.kube/config
     
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog:latest .
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push 676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog
      - echo Writing image definitions file...
      - printf '[{"name":"power-tools","imageUri":"%s"}]' 676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog > imagedefinitions.json
      - echo Applying Kubernetes manifests...
      - kubectl apply --kubeconfig ~/.kube/config -f k8r/deployment.yaml --validate=false
      - kubectl apply --kubeconfig ~/.kube/config -f k8r/service.yaml --validate=false

artifacts:
  files: 
    - imagedefinitions.json
   
