version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog
      - REPOSITORY_URI=676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Logging in to Amazon EKS..."
      - aws eks update-kubeconfig --name interesting-disco-party --region ap-south-1

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog:latest .
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push 676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog
      - echo Writing image definitions file...
      - printf '[{"name":"power-tools","imageUri":"%s"}]' 676206907395.dkr.ecr.ap-south-1.amazonaws.com/power-tools-catalog > imagedefinitions.json
      - echo Updating kubeconfig for EKS...
      - mkdir -p ~/.kube
      - aws eks update-kubeconfig --name interesting-disco-party --region ap-south-1 --kubeconfig ~/.kube/config
      - export KUBECONFIG=~/.kube/config
      - aws sts get-caller-identity
      - kubectl get svc
      - kubectl apply -f k8s/deployment.yaml --validate=false
artifacts:
  files: 
    - imagedefinitions.json
   
